/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * Terminal command identifiers and constants extracted from VS Code terminal module
 */

/**
 * Terminal command enumeration - all available terminal commands
 */
export enum TerminalCommandId {
    Toggle = 'workbench.action.terminal.toggleTerminal',
    Kill = 'workbench.action.terminal.kill',
    KillViewOrEditor = 'workbench.action.terminal.killViewOrEditor',
    KillEditor = 'workbench.action.terminal.killEditor',
    KillActiveTab = 'workbench.action.terminal.killActiveTab',
    KillAll = 'workbench.action.terminal.killAll',
    QuickKill = 'workbench.action.terminal.quickKill',
    ConfigureTerminalSettings = 'workbench.action.terminal.openSettings',
    ShellIntegrationLearnMore = 'workbench.action.terminal.learnMore',
    CopyLastCommand = 'workbench.action.terminal.copyLastCommand',
    CopyLastCommandOutput = 'workbench.action.terminal.copyLastCommandOutput',
    CopyLastCommandAndLastCommandOutput = 'workbench.action.terminal.copyLastCommandAndLastCommandOutput',
    CopyAndClearSelection = 'workbench.action.terminal.copyAndClearSelection',
    CopySelection = 'workbench.action.terminal.copySelection',
    CopySelectionAsHtml = 'workbench.action.terminal.copySelectionAsHtml',
    SelectAll = 'workbench.action.terminal.selectAll',
    DeleteWordLeft = 'workbench.action.terminal.deleteWordLeft',
    DeleteWordRight = 'workbench.action.terminal.deleteWordRight',
    DeleteToLineStart = 'workbench.action.terminal.deleteToLineStart',
    MoveToLineStart = 'workbench.action.terminal.moveToLineStart',
    MoveToLineEnd = 'workbench.action.terminal.moveToLineEnd',
    New = 'workbench.action.terminal.new',
    NewWithCwd = 'workbench.action.terminal.newWithCwd',
    NewLocal = 'workbench.action.terminal.newLocal',
    NewInActiveWorkspace = 'workbench.action.terminal.newInActiveWorkspace',
    NewWithProfile = 'workbench.action.terminal.newWithProfile',
    Split = 'workbench.action.terminal.split',
    SplitActiveTab = 'workbench.action.terminal.splitActiveTab',
    SplitInActiveWorkspace = 'workbench.action.terminal.splitInActiveWorkspace',
    Unsplit = 'workbench.action.terminal.unsplit',
    JoinActiveTab = 'workbench.action.terminal.joinActiveTab',
    Join = 'workbench.action.terminal.join',
    Relaunch = 'workbench.action.terminal.relaunch',
    FocusPreviousPane = 'workbench.action.terminal.focusPreviousPane',
    CreateTerminalEditor = 'workbench.action.createTerminalEditor',
    CreateTerminalEditorSameGroup = 'workbench.action.createTerminalEditorSameGroup',
    CreateTerminalEditorSide = 'workbench.action.createTerminalEditorSide',
    FocusTabs = 'workbench.action.terminal.focusTabs',
    FocusNextPane = 'workbench.action.terminal.focusNextPane',
    ResizePaneLeft = 'workbench.action.terminal.resizePaneLeft',
    ResizePaneRight = 'workbench.action.terminal.resizePaneRight',
    ResizePaneUp = 'workbench.action.terminal.resizePaneUp',
    SizeToContentWidth = 'workbench.action.terminal.sizeToContentWidth',
    SizeToContentWidthActiveTab = 'workbench.action.terminal.sizeToContentWidthActiveTab',
    ResizePaneDown = 'workbench.action.terminal.resizePaneDown',
    Focus = 'workbench.action.terminal.focus',
    FocusNext = 'workbench.action.terminal.focusNext',
    FocusPrevious = 'workbench.action.terminal.focusPrevious',
    Paste = 'workbench.action.terminal.paste',
    PasteSelection = 'workbench.action.terminal.pasteSelection',
    SelectDefaultProfile = 'workbench.action.terminal.selectDefaultShell',
    RunSelectedText = 'workbench.action.terminal.runSelectedText',
    RunActiveFile = 'workbench.action.terminal.runActiveFile',
    SwitchTerminal = 'workbench.action.terminal.switchTerminal',
    ScrollDownLine = 'workbench.action.terminal.scrollDown',
    ScrollDownPage = 'workbench.action.terminal.scrollDownPage',
    ScrollToBottom = 'workbench.action.terminal.scrollToBottom',
    ScrollUpLine = 'workbench.action.terminal.scrollUp',
    ScrollUpPage = 'workbench.action.terminal.scrollUpPage',
    ScrollToTop = 'workbench.action.terminal.scrollToTop',
    Clear = 'workbench.action.terminal.clear',
    ClearSelection = 'workbench.action.terminal.clearSelection',
    ChangeIcon = 'workbench.action.terminal.changeIcon',
    ChangeIconActiveTab = 'workbench.action.terminal.changeIconActiveTab',
    ChangeColor = 'workbench.action.terminal.changeColor',
    ChangeColorActiveTab = 'workbench.action.terminal.changeColorActiveTab',
    Rename = 'workbench.action.terminal.rename',
    RenameActiveTab = 'workbench.action.terminal.renameActiveTab',
    RenameWithArgs = 'workbench.action.terminal.renameWithArg',
    ScrollToPreviousCommand = 'workbench.action.terminal.scrollToPreviousCommand',
    ScrollToNextCommand = 'workbench.action.terminal.scrollToNextCommand',
    SelectToPreviousCommand = 'workbench.action.terminal.selectToPreviousCommand',
    SelectToNextCommand = 'workbench.action.terminal.selectToNextCommand',
    SelectToPreviousLine = 'workbench.action.terminal.selectToPreviousLine',
    SelectToNextLine = 'workbench.action.terminal.selectToNextLine',
    SendSequence = 'workbench.action.terminal.sendSequence',
    SendSignal = 'workbench.action.terminal.sendSignal',
    AttachToSession = 'workbench.action.terminal.attachToSession',
    DetachSession = 'workbench.action.terminal.detachSession',
    MoveToEditor = 'workbench.action.terminal.moveToEditor',
    MoveToTerminalPanel = 'workbench.action.terminal.moveToTerminalPanel',
    MoveIntoNewWindow = 'workbench.action.terminal.moveIntoNewWindow',
    SetDimensions = 'workbench.action.terminal.setDimensions',
    FocusHover = 'workbench.action.terminal.focusHover',
    ShowEnvironmentContributions = 'workbench.action.terminal.showEnvironmentContributions',
    StartVoice = 'workbench.action.terminal.startVoice',
    StopVoice = 'workbench.action.terminal.stopVoice',
}

/**
 * Commands that are commonly used for terminal creation
 */
export const TERMINAL_CREATION_COMMANDS = [
    'workbench.action.terminal.toggleTerminal',
    'workbench.action.terminal.new',
    'workbench.action.togglePanel',
    'workbench.action.terminal.focus'
];

/**
 * Default commands to skip shell processing
 * These commands are handled by the terminal UI directly
 */
export const DEFAULT_COMMANDS_TO_SKIP_SHELL: string[] = [
    TerminalCommandId.ClearSelection,
    TerminalCommandId.Clear,
    TerminalCommandId.CopyAndClearSelection,
    TerminalCommandId.CopySelection,
    TerminalCommandId.CopySelectionAsHtml,
    TerminalCommandId.CopyLastCommand,
    TerminalCommandId.CopyLastCommandOutput,
    TerminalCommandId.CopyLastCommandAndLastCommandOutput,
    TerminalCommandId.DeleteToLineStart,
    TerminalCommandId.DeleteWordLeft,
    TerminalCommandId.DeleteWordRight,
    TerminalCommandId.FocusNextPane,
    TerminalCommandId.FocusNext,
    TerminalCommandId.FocusPreviousPane,
    TerminalCommandId.FocusPrevious,
    TerminalCommandId.Focus,
    TerminalCommandId.SizeToContentWidth,
    TerminalCommandId.Kill,
    TerminalCommandId.KillEditor,
    TerminalCommandId.MoveToEditor,
    TerminalCommandId.MoveToLineEnd,
    TerminalCommandId.MoveToLineStart,
    TerminalCommandId.MoveToTerminalPanel,
    TerminalCommandId.NewInActiveWorkspace,
    TerminalCommandId.New,
    TerminalCommandId.Paste,
    TerminalCommandId.PasteSelection,
    TerminalCommandId.ResizePaneDown,
    TerminalCommandId.ResizePaneLeft,
    TerminalCommandId.ResizePaneRight,
    TerminalCommandId.ResizePaneUp,
    TerminalCommandId.RunActiveFile,
    TerminalCommandId.RunSelectedText,
    TerminalCommandId.ScrollDownLine,
    TerminalCommandId.ScrollDownPage,
    TerminalCommandId.ScrollToBottom,
    TerminalCommandId.ScrollToNextCommand,
    TerminalCommandId.ScrollToPreviousCommand,
    TerminalCommandId.ScrollToTop,
    TerminalCommandId.ScrollUpLine,
    TerminalCommandId.ScrollUpPage,
    TerminalCommandId.SendSequence,
    TerminalCommandId.SelectAll,
    TerminalCommandId.SelectToNextCommand,
    TerminalCommandId.SelectToNextLine,
    TerminalCommandId.SelectToPreviousCommand,
    TerminalCommandId.SelectToPreviousLine,
    TerminalCommandId.SplitInActiveWorkspace,
    TerminalCommandId.Split,
    TerminalCommandId.Toggle,
    TerminalCommandId.FocusHover,
    // Additional workbench commands
    'editor.action.toggleTabFocusMode',
    'notifications.hideList',
    'notifications.hideToasts',
    'workbench.action.closeQuickOpen',
    'workbench.action.quickOpen',
    'workbench.action.quickOpenPreviousEditor',
    'workbench.action.showCommands',
    'workbench.action.tasks.build',
    'workbench.action.tasks.restartTask',
    'workbench.action.tasks.runTask',
    'workbench.action.tasks.reRunTask',
    'workbench.action.tasks.showLog',
    'workbench.action.tasks.showTasks',
    'workbench.action.tasks.terminate',
    'workbench.action.tasks.test',
    'workbench.action.toggleFullScreen',
    'workbench.action.terminal.focusAtIndex1',
    'workbench.action.terminal.focusAtIndex2',
    'workbench.action.terminal.focusAtIndex3',
    'workbench.action.terminal.focusAtIndex4',
    'workbench.action.terminal.focusAtIndex5',
    'workbench.action.terminal.focusAtIndex6',
    'workbench.action.terminal.focusAtIndex7',
    'workbench.action.terminal.focusAtIndex8',
    'workbench.action.terminal.focusAtIndex9',
    'workbench.action.focusSecondEditorGroup',
    'workbench.action.focusThirdEditorGroup',
    'workbench.action.focusFourthEditorGroup',
    'workbench.action.focusFifthEditorGroup',
    'workbench.action.focusSixthEditorGroup',
    'workbench.action.focusSeventhEditorGroup',
    'workbench.action.focusEighthEditorGroup',
    'workbench.action.focusNextPart',
    'workbench.action.focusPreviousPart',
    'workbench.action.nextPanelView',
    'workbench.action.previousPanelView',
    'workbench.action.nextSideBarView',
    'workbench.action.previousSideBarView',
    'workbench.action.debug.disconnect',
    'workbench.action.debug.start',
    'workbench.action.debug.stop',
    'workbench.action.debug.run',
    'workbench.action.debug.restart',
    'workbench.action.debug.continue',
    'workbench.action.debug.pause',
    'workbench.action.debug.stepInto',
    'workbench.action.debug.stepOut',
    'workbench.action.debug.stepOver',
    'workbench.action.nextEditor',
    'workbench.action.previousEditor',
    'workbench.action.nextEditorInGroup',
    'workbench.action.previousEditorInGroup',
    'workbench.action.openNextRecentlyUsedEditor',
    'workbench.action.openPreviousRecentlyUsedEditor',
    'workbench.action.openNextRecentlyUsedEditorInGroup',
    'workbench.action.openPreviousRecentlyUsedEditorInGroup',
    'workbench.action.quickOpenPreviousRecentlyUsedEditor'
];

/**
 * Quick launch profile choice command
 */
export const QUICK_LAUNCH_PROFILE_CHOICE = 'workbench.action.terminal.profile.choice';

/**
 * Terminal command groups for categorization
 */
export const TerminalCommandGroups = {
    creation: [
        TerminalCommandId.New,
        TerminalCommandId.NewWithCwd,
        TerminalCommandId.NewLocal,
        TerminalCommandId.NewInActiveWorkspace,
        TerminalCommandId.NewWithProfile
    ],
    navigation: [
        TerminalCommandId.Focus,
        TerminalCommandId.FocusNext,
        TerminalCommandId.FocusPrevious,
        TerminalCommandId.FocusNextPane,
        TerminalCommandId.FocusPreviousPane,
        TerminalCommandId.SwitchTerminal
    ],
    editing: [
        TerminalCommandId.CopySelection,
        TerminalCommandId.CopyAndClearSelection,
        TerminalCommandId.Paste,
        TerminalCommandId.PasteSelection,
        TerminalCommandId.SelectAll,
        TerminalCommandId.Clear,
        TerminalCommandId.ClearSelection
    ],
    management: [
        TerminalCommandId.Kill,
        TerminalCommandId.KillAll,
        TerminalCommandId.Relaunch,
        TerminalCommandId.Rename,
        TerminalCommandId.ChangeIcon,
        TerminalCommandId.ChangeColor
    ],
    layout: [
        TerminalCommandId.Split,
        TerminalCommandId.Unsplit,
        TerminalCommandId.Join,
        TerminalCommandId.ResizePaneLeft,
        TerminalCommandId.ResizePaneRight,
        TerminalCommandId.ResizePaneUp,
        TerminalCommandId.ResizePaneDown
    ]
} as const;